### ISSUE TITLE
Tunnel zhangyx.vaiwan.com:8081 not found

### ISSUE THREAD

**Issue by xiaoxinshiwo** [open-dingtalk/pierced#12]
你好，使用钉钉官网的教程启动内网穿透工具，启动命令：
./ding -config=./ding.cfg -subdomain=zhangyx 8079
访问报错如下：
Tunnel zhangyx.vaiwan.com:8081 not found
求解

**Comment by xiaoxinshiwo** [comment]
ngrok                                                                                                                                                                                                                           (Ctrl+C to quit)
                                                                                                                                                                                                                                                
Tunnel Status                 connecting                                                                                                                                                                                                        
Version                       1.7/                                                                                                                                                                                                              
Web Interface                 127.0.0.1:4040                                                                                                                                                                                                    
# Conn                        0                                                                                                                                                                                                                 
Avg Conn Time                 0.00ms

**Comment by xiaoxinshiwo** [comment]
启动后命令行展示如下：
![image](https://user-images.githubusercontent.com/24218496/68659652-986e5680-0572-11ea-8a57-a91fd0664644.png)

**Comment by firelph** [comment]
解决了吗

**Comment by xiaoxinshiwo** [comment]
> 解决了吗

解决了，因为在公司内网，形成了一个闭环，我回家就是好的
