### ISSUE TITLE
reconnecting

### ISSUE THREAD

**Issue by SnakeHacker** [open-dingtalk/pierced#26]

**Comment by badafans** [comment]
dingtalk stopped public forwardproxy server

**Comment by cute2tiger** [comment]
连不上了，是暂时的还是永远连不上?

**Comment by feiyu563** [comment]
同问
![image](https://user-images.githubusercontent.com/25146052/98775413-12584a80-2428-11eb-9244-e0d4a65e845a.png)

**Comment by SnakeHacker** [comment]
可以了 赞

**Comment by directmemory** [comment]
是时候说永远了吗？
