### ISSUE TITLE
终端报错：Segmentation fault

### ISSUE THREAD

**Issue by Jairwin-L** [open-dingtalk/pierced#35]
```bash
./ding -config=./ding.cfg -subdomain=abcde 8080
```
![image](https://user-images.githubusercontent.com/32570960/117798018-3daadd80-b283-11eb-9502-f47b5eb9d4dd.png)

**Comment by liangxp** [comment]
请教楼主怎么解决的？我M1也是同样的错误！

**Comment by jetBn** [comment]
怎么解决的？
