### ISSUE TITLE
Windows版本案例能不能出一个?

### ISSUE THREAD

**Issue by robot1d59cc305** [open-dingtalk/pierced#5]
windows下版本的使用案例出一个.

**Comment by SweetInk** [comment]
下载[`windows`](https://github.com/open-dingtalk/pierced/tree/master/windows_64) 版本工具后
打开`power shell` 或者 `cmd`
```bat
cd windows_64
ding.exe -config=ding.cfg -proto=tcp start ssh
```
更多使用方式参考[ngrok 搭建内网穿透+远程桌面连接](https://blog.csdn.net/liushimiao0104/article/details/83025680)

**Comment by robot1d59cc305** [comment]
> 下载[`windows`](https://github.com/open-dingtalk/pierced/tree/master/windows_64) 版本工具后
> 打开 `cmd`
> 
> ```batchfile
> cd windows_64
> ding.exe -config=ding.cfg -proto=tcp start ssh
> ```
> 
> 更多使用方式参考[ngrok 搭建内网穿透+远程桌面连接](https://blog.csdn.net/liushimiao0104/article/details/83025680)

链接挂了。

**Comment by robot1d59cc305** [comment]
> 下载[`windows`](https://github.com/open-dingtalk/pierced/tree/master/windows_64) 版本工具后
> 打开 `cmd`
> 
> ```batchfile
> cd windows_64
> ding.exe -config=ding.cfg -proto=tcp start ssh
> ```
> 
> 更多使用方式参考[ngrok 搭建内网穿透+远程桌面连接](https://blog.csdn.net/liushimiao0104/article/details/83025680)
