### ISSUE TITLE
去年还能用，今年是用不了吗

### ISSUE THREAD

**Issue by showmetime** [open-dingtalk/pierced#73]

**Comment by woody3rd** [comment]
因安全合规、服务资源和维护成本等原因，钉钉于2022年7月21日起，不再提供内网穿透的工具服务，若需要在本地或开发测试环境调试中有内网穿透的需求，请参考文档自行搭建的[frp内网穿透工具](https://open.dingtalk.com/document/resourcedownload/alibaba-cloud-frp-intranet-penetration-tool#)。

**Comment by chzealot** [comment]
推荐采用最新推出的 Stream 模式 5分钟快速接入：


“钉钉开放平台Stream模式共创群”群的钉钉群号： 35365014813
https://qr.dingtalk.com/action/joingroup?code=v1,k1,NrXMLmpJdhjHp1OEGUdSy4zSfaGjzAjiC9VWxMHECmg=&_dt_no_comment=1&origin=11? 金喜(主用钉)邀请你加入钉钉群聊钉钉开放平台Stream模式共创群，点击进入查看详情

![stream](https://github.com/open-dingtalk/pierced/assets/22822/50d15d55-a06b-4ed5-b818-214b133f51e4)
